services:
  selenoid:
    image: "aerokube/selenoid:latest"
    container_name: selenoid
    ports:
      - "4444:4444"
    network_mode: bridge
    volumes:
      - ".:/etc/selenoid"
      - "./target:/output"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./target:/opt/selenoid/video"
    environment:
      - "OVERRIDE_VIDEO_OUTPUT_DIR=/Users/solvd/Downloads/vid"
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video"]
  chrome_100.0:
    image: "sskorol/selenoid_chromium_vnc:100.0"
    container_name: chrome_100.0
    network_mode: bridge
    links:
      - selenoid
    volumes:
      - "/dev/shm:/dev/shm"
  firefox:
    image: "selenoid/firefox:109.0"
    network_mode: bridge
    links:
      - selenoid
  video:
    image: selenoid/video-recorder:latest-release
    network_mode: bridge
    links:
      - selenoid
  ggr:
    image: aerokube/ggr:latest-release
    container_name: ggr
    network_mode: bridge
    ports:
      - 4445:4444
    links:
      - selenoid
    volumes:
      - ./grid-router:/etc/grid-router:ro